version: '3'
services:
  drupal:
    build: "./.docker/"
    container_name: drupal
    volumes:
    - "./env/settings.local.php:/var/www/html/sites/default/settings.php"
    - "./src/files:/var/www/html/sites/default/files/"
    - "./src/modules/contrib:/var/www/html/modules/contrib/"
    ports:
    - "80:80"
    - "443:443"
    links:
    - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_DATABASE=drupal
